AllCops:
  Exclude:
    - 'spec/spec_helper.rb'
Style/Documentation:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Layout/LineLength:
  Max: 90
Metrics/BlockLength:
  Exclude:
  - 'spec/*'
  - 'green_day.gemspec'
