require: 
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'spec/spec_helper.rb'
Style/Documentation:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Layout/LineLength:
  Max: 90
Metrics/BlockLength:
  Exclude:
  - 'spec/*/**'
  - 'green_day.gemspec'
RSpec/NamedSubject:
  Enabled: false
RSpec/NestedGroups:
  Max: 4
RSpec/ExampleLength:
  Enabled: false