name: Bump version and Push to RubyGems

on:
  workflow_dispatch:
    inputs:
      miner-or-major:
        description: 'Minor or major release'
        required: true
        default: 'minor'
        options:
          - 'minor'
          - 'major'
      email:
        description: Your email
        required: true
        type: string


jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby 3.2
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - run: bundle install
      - run: gem install gem-release

      - name: config
        run: |
          git config --global user.email ${{ github.event.inputs.email }}
          git config --global user.name ${{ github.actor }}

      - name: Bump version
        run: gem bump --version ${{ github.event.inputs.miner-or-major }}

      - name: Publish to RubyGems
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          gem build *.gemspec
          gem push *.gem
        env:
          GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"
