name: Ruby

on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  rspec:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version:
          - 3.2.1 # Atcoderが採用しているバージョン
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Bundle install
        run: bundle install
      - name: Run Rspec
        env:
          USER_NAME: ${{ secrets.USER_NAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: script -e -c "rake spec"
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.1
      - name: Bundle install
        run: bundle install
      - name: Run rubocop
        run: bundle exec rubocop
      


