name: Ruby

on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  rspec:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - 2.7.1 # AtCoder公式が使用しているrubyは2.7.1
          - 3.1.0
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: bundle install
        run: bundle install
      - name: Rubocop
        run: bundle exec rubocop
      - name: Rspec
        env:
          USER_NAME: ${{ secrets.USER_NAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: script -e -c "rake spec"
      


